-- CreateTable
CREATE TABLE `Inscritos` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `nome` VARCHAR(191) NOT NULL,
    `telefone` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191) NOT NULL,
    `senha` VARCHAR(191) NOT NULL,
    `endereco` VARCHAR(191) NOT NULL,
    `cidade` VARCHAR(191) NOT NULL,
    `estado` VARCHAR(191) NOT NULL,
    `data_nascimento` DATETIME(3) NOT NULL,
    `categoria` VARCHAR(191) NOT NULL,
    `fotoCompetidor` VARCHAR(191) NOT NULL,
    `cpf` VARCHAR(191) NOT NULL,
    `idade` INTEGER NOT NULL,
    `genero` VARCHAR(191) NOT NULL,
    `graduacao` VARCHAR(191) NOT NULL,
    `peso` DOUBLE NOT NULL,
    `equipe` VARCHAR(191) NOT NULL,
    `equipeImg` VARCHAR(191) NULL,
    `professor` VARCHAR(191) NOT NULL,
    `responsavel` VARCHAR(191) NULL,
    `cpfResp` VARCHAR(191) NULL,
    `fotoResp` VARCHAR(191) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `Inscritos_email_key`(`email`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
