-- AlterTable
ALTER TABLE `luta` ADD COLUMN `faltas1` INTEGER NULL,
    ADD COLUMN `faltas2` INTEGER NULL,
    ADD COLUMN `montada1` INTEGER NULL DEFAULT 0,
    ADD COLUMN `montada2` INTEGER NULL DEFAULT 0,
    ADD COLUMN `passagem1` INTEGER NULL DEFAULT 0,
    ADD COLUMN `passagem2` INTEGER NULL DEFAULT 0,
    ADD COLUMN `pontos1` INTEGER NULL,
    ADD COLUMN `pontos2` INTEGER NULL,
    ADD COLUMN `raspagem1` INTEGER NULL DEFAULT 0,
    ADD COLUMN `raspagem2` INTEGER NULL DEFAULT 0,
    ADD COLUMN `tempo` INTEGER NULL,
    ADD COLUMN `vantagens1` INTEGER NULL,
    ADD COLUMN `vantagens2` INTEGER NULL;
